2020-05-16 08:06:01,777:Survey Assist - v1.0:Started Application
2020-05-16 08:28:32,544:Survey Assist - v1.0:Started Application
2020-05-16 08:33:38,418:Survey Assist - v1.0:Started Application
2020-05-16 08:35:59,780:Survey Assist - v1.0:Started Application
2020-05-16 09:09:05,106:Survey Assist - v1.0:Started Application
2020-05-16 09:17:56,337:Survey Assist - v1.0:Started Application
2020-05-16 09:18:56,751:Survey Assist - v1.0:Started Application
2020-05-16 09:22:43,879:Survey Assist - v1.0:Started Application
2020-05-16 10:37:27,321:Survey Assist - v1.0:Started Application
2020-05-16 10:39:26,643:Survey Assist - v1.0:Started Application
2020-05-16 10:41:54,155:Survey Assist - v1.0:Started Application
2020-05-16 10:45:46,335:Survey Assist - v1.0:Started Application
2020-05-16 10:46:37,352:Survey Assist - v1.0:Started Application
2020-05-16 10:47:23,188:Survey Assist - v1.0:Started Application
2020-05-16 10:48:15,116:Survey Assist - v1.0:Started Application
2020-05-16 10:50:11,737:Survey Assist - v1.0:Started Application
2020-05-16 10:52:11,366:Survey Assist - v1.0:Started Application
2020-05-16 10:52:37,362:Survey Assist - v1.0:Started Application
2020-05-16 10:53:02,128:Survey Assist - v1.0:Started Application
2020-05-18 15:31:51,230:Survey Assist - v1.0:Started Application
2020-05-18 15:34:04,278:Survey Assist - v1.0:Started Application
2020-05-18 15:34:22,100:Survey Assist - v1.0:Started Application
2020-05-18 15:38:38,204:Survey Assist - v1.0:Started Application
2020-05-18 15:52:58,248:Survey Assist - v1.0:Started Application
2020-05-18 15:54:23,321:Survey Assist - v1.0:Started Application
2020-05-18 15:54:41,056:Survey Assist - v1.0:Started Application
2020-05-18 15:54:43,453:Survey Assist - v1.0:An unexpected error has occurred

btn_job_tracker()

[WinError 2] The system cannot find the file specified: 'C:\\Users\\Richard\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 1385, in btn_job_tracker
    os.startfile(job_tracker_filepath)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Richard\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
2020-05-18 15:55:52,856:Survey Assist - v1.0:Started Application
2020-05-18 15:55:55,034:Survey Assist - v1.0:An unexpected error has occurred

btn_job_tracker()

[WinError 2] The system cannot find the file specified: 'C:\\Users\\Richard\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 1385, in btn_job_tracker
    os.startfile(job_tracker_filepath)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Richard\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
2020-05-18 15:56:43,124:Survey Assist - v1.0:Started Application
2020-05-18 15:56:45,002:Survey Assist - v1.0:An unexpected error has occurred

btn_job_tracker()

[WinError 2] The system cannot find the file specified: 'C:\\Users\\Richard\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 1385, in btn_job_tracker
    os.startfile(self.job_tracker_filepath)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Richard\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
2020-05-18 15:57:16,669:Survey Assist - v1.0:Started Application
2020-05-18 15:57:27,001:Survey Assist - v1.0:An unexpected error has occurred

btn_job_tracker()

[WinError 2] The system cannot find the file specified: 'C:\\Users\\Richard\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 1385, in btn_job_tracker
    os.startfile(self.job_tracker_filepath)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Richard\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
2020-05-18 16:00:32,508:Survey Assist - v1.0:Started Application
2020-05-18 16:03:32,865:Survey Assist - v1.0:Started Application
2020-05-18 16:05:37,166:Survey Assist - v1.0:Started Application
2020-05-18 16:06:01,811:Survey Assist - v1.0:Started Application
2020-05-18 16:06:12,302:Survey Assist - v1.0:Started Application
2020-05-18 16:06:38,655:Survey Assist - v1.0:Started Application
2020-05-18 16:07:29,943:Survey Assist - v1.0:Started Application
2020-05-18 16:09:55,494:Survey Assist - v1.0:Started Application
2020-05-18 16:10:39,414:Survey Assist - v1.0:Started Application
2020-05-18 16:11:10,375:Survey Assist - v1.0:An unexpected error has occurred

btn_job_tracker()

[WinError 2] The system cannot find the file specified: 'C:\\Users\\Richard\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 1390, in btn_job_tracker
    os.startfile(self.job_tracker_filepath)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\Richard\\PycharmProjects\\Survey Assist\\Test Files\\Survey Data\\2020\\Job Tracker Digital System.xlsm'
2020-05-18 16:38:53,117:Survey Assist - v1.0:Started Application
2020-05-18 16:39:02,532:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200515/ARTC_903_MON_V2_TS60_150520_EDITED_Sorted_PCUpdated.gsi
2020-05-18 16:40:20,673:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200503/ARTC_903_MON_V2_MS60_030520_EDITED_PCUpdated_Sorted.gsi
2020-05-18 16:40:47,216:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/ARTC_903_compnet 240220.GSI
2020-05-18 19:08:14,654:Survey Assist - v1.0:Started Application
2020-05-18 19:08:41,955:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-18 19:09:14,900:Survey Assist - v1.0:Started Application
2020-05-18 19:09:22,424:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-18 19:11:19,313:Survey Assist - v1.0:Started Application
2020-05-18 19:11:30,034:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-18 19:11:47,816:Survey Assist - v1.0:An unexpected error has occurred

check_FLFR()

could not convert string to float: 
Traceback (most recent call last):
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 678, in check_FLFR
    analysed_lines = self.anaylseFLFR(copy.deepcopy(obs_from_station_dict))
  File "C:/Users/Richard/PycharmProjects/Survey Assist/main.py", line 780, in anaylseFLFR
    obs_line_2_field_value = get_numerical_value_from_string(obs_line_2_field_value_str, field_type, precision)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\utilities.py", line 83, in get_numerical_value_from_string
    return angle_DMS_2_decimal(angle_deg, angle_min, angle_sec)
  File "C:\Users\Richard\PycharmProjects\Survey Assist\utilities.py", line 42, in angle_DMS_2_decimal
    return float(angle_deg) + float(angle_min) / 60 + float(angle_sec) / (60 * 60)
ValueError: could not convert string to float: 
2020-05-18 19:17:54,657:Survey Assist - v1.0:Started Application
2020-05-18 19:18:00,877:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-18 19:18:21,849:Survey Assist - v1.0:Started Application
2020-05-18 19:18:28,471:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-18 19:20:15,112:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-18 19:22:06,162:Survey Assist - v1.0:Started Application
2020-05-18 19:22:11,394:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-18 19:23:04,002:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-18 19:23:14,189:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-18 19:27:06,049:Survey Assist - v1.0:Started Application
2020-05-18 19:27:10,798:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/Downloads/890MR 150520.GSI
2020-05-18 19:28:04,189:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/Richard/PycharmProjects/Survey Assist/Test Files/GSI Files/3D MR_120819_3D error change_EDITED.gsi
2020-05-18 22:21:07,767:Survey Assist - v1.0:Started Application
2020-05-20 15:40:34,435:Survey Assist - v1.0:Started Application
2020-05-20 16:03:46,606:Survey Assist - v1.0:Started Application
2020-05-20 16:06:57,775:Survey Assist - v1.0:Started Application
2020-05-20 16:07:24,059:Survey Assist - v1.0:Started Application
2020-05-20 16:09:30,217:Survey Assist - v1.0:Started Application
2020-05-20 16:12:02,987:Survey Assist - v1.0:Started Application
2020-05-20 16:12:59,132:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520.GSI
2020-05-20 16:13:04,023:Survey Assist - v1.0:An unexpected error has occurred

check_FLFR()

could not convert string to float: 
Traceback (most recent call last):
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 681, in check_FLFR
    analysed_lines = self.anaylseFLFR(copy.deepcopy(obs_from_station_dict))
  File "C:/Users/rjwal_000/PycharmProjects/Survey Assist/main.py", line 783, in anaylseFLFR
    obs_line_2_field_value = get_numerical_value_from_string(obs_line_2_field_value_str, field_type, precision)
  File "C:\Users\rjwal_000\PycharmProjects\Survey Assist\utilities.py", line 83, in get_numerical_value_from_string
    return angle_DMS_2_decimal(angle_deg, angle_min, angle_sec)
  File "C:\Users\rjwal_000\PycharmProjects\Survey Assist\utilities.py", line 42, in angle_DMS_2_decimal
    return float(angle_deg) + float(angle_min) / 60 + float(angle_sec) / (60 * 60)
ValueError: could not convert string to float: 
2020-05-20 16:21:23,430:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719.GSI
2020-05-20 16:23:54,508:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/2D Survey MR050819.GSI
2020-05-20 16:24:02,586:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520.GSI
2020-05-20 16:24:09,321:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/Survey Data/2020/MONITORING/A9 ARTC/200515/ARTC_903_MON_V2_TS60_150520_EDITED_Sorted.gsi
2020-05-20 16:24:21,617:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCUL180219.GSI
2020-05-20 16:32:15,789:Survey Assist - v1.0:Started Application
2020-05-20 16:32:24,367:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCUL180219.GSI
2020-05-20 16:32:40,900:Survey Assist - v1.0:Started Application
2020-05-20 16:32:45,742:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCUL180219.GSI
2020-05-20 16:33:11,192:Survey Assist - v1.0:Started Application
2020-05-20 16:33:15,617:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCUL180219.GSI
2020-05-20 16:34:32,144:Survey Assist - v1.0:Started Application
2020-05-20 16:34:36,804:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCUL180219.GSI
2020-05-20 16:38:20,366:Survey Assist - v1.0:Started Application
2020-05-20 16:38:27,555:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCUL180219.GSI
2020-05-20 16:38:54,505:Survey Assist - v1.0:Started Application
2020-05-20 16:38:59,321:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCUL180219.GSI
2020-05-20 16:45:21,018:Survey Assist - v1.0:Started Application
2020-05-20 16:45:25,554:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCUL180219.GSI
2020-05-20 16:45:47,414:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520.GSI
2020-05-20 16:46:14,747:Survey Assist - v1.0:Started Application
2020-05-20 16:46:18,930:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCUL180219.GSI
2020-05-20 16:46:35,523:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719.GSI
2020-05-20 16:47:32,851:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520.GSI
2020-05-20 16:50:22,273:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/PycharmProjects/Survey Assist/Test Files/GSI Files/HCCL 030719.GSI
2020-05-20 16:52:49,372:Survey Assist - v1.0:Started Application
2020-05-20 16:52:58,477:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520.GSI
2020-05-20 16:54:39,711:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/Raumer fix 150520_Sorted.gsi
2020-05-20 16:55:11,867:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/890MR 150520.GSI
2020-05-20 16:55:39,117:Survey Assist - v1.0:OPENING UP A GSI FILE: C:/Users/rjwal_000/Downloads/Raumer fix 150520_Sorted.gsi
